Add epimodel-covid-data as submodule
epidemics/epimodel pull request #38
Opened 2020-04-18 18:55 UTC by hnykda

We have a heavy dependency on the data module, i.e. this repository main entrypoints/commands are not usable without having the right version of https://github.com/epidemics/epimodel-covid-data (as has been shown in the last few days). 

I propose we put data as it's own submodule and therefore have guarantee that we can run the master branch as is and also develop stuff independently depending on what branch from this repo need a branch from other one.

2020-04-18 19:28 UTC, mathijshenquet approved these changes
:+1:

2020-04-18 20:23 UTC, gavento commented
I thought about this and I see one problem: 
I understand that the submodule ISH is recorded in the parent repo, and updating the submodule aslo needs a commit in the parent repo. 
* This would tie these together in a way we wanted to avoid by having two repos.
* This will force all of us to update the submodule reference in our dev branches at different points. Merging diverged submodules is [not trivial](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

Please correct me if I am wrong and updating submodule does not need a commit in parent repo.

2020-04-18 20:25 UTC, gavento requested changes
See my comment, I think that even `data` record in "Files changed" PR tab points to a fixed revision of data.

2020-04-18 20:46 UTC, hnykda commented
I don't really care that much, I realize that adding submodules is another bit of complexity. But here are my thoughts:

> This would tie these together in a way we wanted to avoid by having two repos.

But we have tied them together already data-wise, otherwise we couldn't break this repo by changing the other one, which has happened for several times these days. So we maybe didn't wanted, but we clearly did. Me changing a file in that repo breaks some functionality in this repo... We can pretend that they are not tied, but they inevitably are :grin: .

> This will force all of us to update the submodule reference in our dev branches

Which is IMO inevitable, because of the above. The alternative now is:
1. hoping that files are still consistent and same (which hasn't been the case)
2. finding out which commit worked when by themselves via trial and error

> Merging diverged submodules is not trivial

I am not really sure what this one means, whenever I used submodules I was able to nicely resolve conflicts the same way as with regular repos.

2020-04-24 17:55 UTC, gavento commented
@hnykda In my view, the main use cases of epimodel-covid-data are:
* Shared base files (regions.csv) - only minor updates, but I generally want to have fixes to that everywhere.
* Shared updated JH and FT data - same as above, unless broken, these are updated incrementally
* Data for countermeasure models - same as above, I want updates easily distributable
  * Otherwise I would need to make sure I update the files everywhere where I run any code
  * David removed some older ones, breaking many older files, so we may need norms here
* Misc other files - beds, ... mostly not updated, but removal may break stuff (but they have narrow scope)
* Sources and misc data files for reference, these can be just piled on

Submodules with fixed version would prevent basically all of this. Do you have a better solution?

2020-04-24 17:56 UTC, gavento commented
@hnykda Have you worked with modules that are updated independently, e.g. in branches? I read that merging them is hell, and modules are complex additional logic.

2020-04-24 18:49 UTC, mathijshenquet commented
Linking a specific version of a repo as a submodule is the whole point isn't it?

From my perspective the 3 repo thing we have going on is rather a pain to work with. If you want to add a thing to the site which needs data, some processing in epimodel and frontend code you have to make 3 PR's to coordinate all these parts together. It also makes deployment rather tricky, especially when you make a potentially non backward compatible change.

How about putting eveything in one big repo (again)? When I'm looking at your points I think that 
might actually make a lot of sense:
- `/web/` containing the contents of the `covid` repo
- `/epimodel/` contains most of the `epimodel` repo
- `/data/` contains the `epimodel-data` repo
- `/notebooks/` (or whatever) is where people can store their stuff work depending on `/data/`

(This is roughly how I've set things up locally, with `/epimodel/data` symlinked to `/data`)

2020-04-24 19:59 UTC, hnykda commented
Tomas is working mostly with these and if you don't like it, then I don't think it makes sense, I don't have any more arguments then I said and I clearly assumed different dev style.

To recap my thoughts. The current solution means that the same commit working in t0 doesn't run anymore in t1. It's impossible to guess what version of data worked with the current master (and it doesn't work without the data folder). It enables being "latest everywhere by default" (which is 
a feature in a sense), but in the same time brings complications mentioned earlier. I think that submodules complexity is a good price, but it's surely subjective.

> Linking a specific version of a repo as a submodule is the whole point isn't it?

Yes

> How about putting eveything in one big repo (again)?

I think it would be better than the current scenario. But I also think it's fine to separate data generation from the presentation layer, especially given the technologies are entirely different.

2020-04-24 20:00 UTC, closed without merging